### ISSUE TITLE
double plotted actogram

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/rethomics#11]
a prototype 

``` R
library(data.table)
library(ggplot2)
# we build some dummy data with a period of 25.4h
set.seed(1)
n= 15*24 + 3
dt <- data.table(t=1:n)
dt[, y := abs(sin(2*pi*t/25.4)) + rnorm(n,1,0.2)]

dt[,t_in_day := t%%24]
dt[,day := floor(t/24)]
dt2 <- copy(dt)
dt2[,day := day-1]

dt2[,t_in_day := t_in_day + 24]
dt <- dt[day<max(day)]
dd <- rbind(dt, dt2)
dd <- dd[day>-1]

dd[, day_str := sprintf("day\n%03d",day)]

ggplot(dd,aes(t_in_day,ymax=y, ymin=min(y))) +
        geom_ribbon() + 
        facet_grid(day_str ~ .) + scale_x_continuous(name="time (h)",breaks = 0:8 * 6)+
         scale_y_continuous(name="y")
```

![double_plot_acto](https://cloud.githubusercontent.com/assets/1399684/8692083/85c840ca-2ac2-11e5-8657-7fe56179a3f2.png)

**Comment by qgeissmann** [comment]
Instead of per-animal actograms, I think it would work better to use a tiled plot (http://docs.ggplot2.org/current/geom_tile.html) btw. 
This should be faster to read, smaller and more consise.

**Comment by qgeissmann** [comment]
So it would look like that in a tiled plot:
![rplots](https://cloud.githubusercontent.com/assets/1399684/8692380/9ecf9872-2ac5-11e5-8f40-a5942b2e8042.png)

```R
dd[, day_str := as.ordered(day)]
dd[, day_str := ordered(day_str,levels=rev(levels(day_str)))]

ggplot(dd,aes(t_in_day,y=day_str, fill=y)) +
		 geom_tile()+
		 scale_x_continuous(name="time (h)",breaks = 0:8 * 6) +
		 scale_y_discrete(name="starting day")
```

**Comment by zoranne** [comment]
R u including circadian analysis? Amazing!!!

**Comment by qgeissmann** [comment]
Basically yes. 
The structure of the package should allow various analysis such as : 

* sleep
* circadian rhythm
* location preference
* trajectory
* response time analysis

Hopefully, with contribution, we can make this a nice toolbox

**Comment by zoranne** [comment]
Booom! What can I do?

**Comment by Elizabeth321** [comment]
Hi, everyone, I want to make a actogram with bar type for each data point and color them according to their values. I used the prototype as above, but when I use the codes below, the graph showed the data points in wrong order (just one after another according to the table without grouping them into the right facet (based on their day_str information). Do you have any idea? Really appreciate it.

codes : 

ggplot(dd1,aes(x=t_in_day,y=y)) +
      geom_bar(stat="identity",aes(fill=col1)) + 
      facet_grid(day_str ~ .) + scale_x_continuous(name="time (h)",breaks = waiver())+
      scale_y_continuous(name="y") + #scale_colour_gradient(low="red", high="yellow")+
      scale_fill_manual(values=rbPal(break1),labels=cuts)

**Comment by qgeissmann** [comment]
hey @Elizabeth321, rethomics has been refactored into several packages in the last year.
The new framework should work much better. you can read about it at https://rethomics.github.io/. We also support double-plotted actograms etc. I hope it helps!

**Comment by qgeissmann** [comment]
see the new rethomics: https://rethomics.github.io/ggetho.html#double-plotted-actograms

**Comment by Elizabeth321** [comment]
Hi, @qgeissmann, I read the website. I will try it later. The only thing I worried is that is there a way to color the barplot? I want to color the data points based on their values. Thank you so much
