### ISSUE TITLE
Wrong date in DAM file loading  for data before 2015

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/rethomics#12]
The date appears to be in 2015 regardless of query date (e.g. 2014).

**Comment by zoranne** [comment]
o.o panic!!

On 16 July 2015 at 14:06, Quentin Geissmann <notifications@github.com>
wrote:

> Closed #12 <https://github.com/gilestrolab/rethomics/issues/12> via
> b0bf662
> <https://github.com/gilestrolab/rethomics/commit/b0bf662636c9f42076dcd7d4b899adca203dfade>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gilestrolab/rethomics/issues/12#event-357494257>.
>



-- 
___________________________________
PhD Life Sciences Candidate
Graduate School
Life Sciences Department
South Kensington Campus
Imperial College London
___________________________________
Integrative Neuroscience, M.Sc.
Philosophy of Neuroscience, B.A.

**Comment by qgeissmann** [comment]
don't worry, this is fixed by b0bf662
