### ISSUE TITLE
data fetcher should use only the name of the db not the directory structure

### ISSUE THREAD

**Issue by PolygonalTree** [gilestrolab/rethomics#16]
When you load PsvResult file using the function "fetchPsvResultFiles" it show an error if the selected directory does not contain 4 subdirectories. The program takes information from the name of this directory such as machine id, date ... 
Not all users has the same directory structure and we shouldn't force to use one in particular, I think is better to take this information from the name of the file.

**Comment by PolygonalTree** [comment]
I have discover the loadPSVData, maybe the last comment has not sense.

**Comment by qgeissmann** [comment]
probably means we should interlink functions a bit more (using the `@seealso` tag).
