### ISSUE TITLE
'fetchDAMData' should ignore row stamp

### ISSUE THREAD

**Issue by zoranne** [gilestrolab/rethomics#21]
Problem seems to be that 'fetchDAMData' recognises row stamps that do not start with 1 as repeated time stamps. There are several DAM files where time stamps are fine, but rows do not start with 1.

**Comment by qgeissmann** [comment]
This seems to be a problem in hos daily data are generated. TBC

**Comment by zoranne** [comment]
yes, it works for other files where the row stamp doesn't start with 1
either...

On 3 August 2015 at 17:28, Quentin Geissmann <notifications@github.com>
wrote:

> This seems to be a problem in hos daily data are generated. TBC
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gilestrolab/rethomics/issues/21#issuecomment-127308966>
> .
>



-- 
___________________________________
PhD Life Sciences Candidate
Graduate School
Life Sciences Department
South Kensington Campus
Imperial College London
___________________________________
Integrative Neuroscience, M.Sc.
Philosophy of Neuroscience, B.A.

**Comment by qgeissmann** [comment]
An example of a simple case were we have erroneous time stamp:
```
5569	21 Jul 15	15:02:00	54	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
5570	21 Jul 15	15:03:00	54	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
5571	21 Jul 15	15:04:00	54	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1	21 Jul 15	15:06:00	54	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
1	21 Jul 15	15:06:00	54	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
```
We should use the status message of DAM (e.g. 54) in order to exclude/keep data too.

**Comment by zoranne** [comment]
yes! along with the light detection... :)

On 3 August 2015 at 17:57, Quentin Geissmann <notifications@github.com>
wrote:

> An example of a simple case were we have erroneous time stamp:
>
> 5569    21 Jul 15   15:02:00    54  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
> 5570    21 Jul 15   15:03:00    54  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
> 5571    21 Jul 15   15:04:00    54  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
> 1   21 Jul 15   15:06:00    54  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
> 1   21 Jul 15   15:06:00    54  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
>
> We should use the status message of DAM (e.g. 54) in order to exclude/keep
> data too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gilestrolab/rethomics/issues/21#issuecomment-127331020>
> .
>



-- 
___________________________________
PhD Life Sciences Candidate
Graduate School
Life Sciences Department
South Kensington Campus
Imperial College London
___________________________________
Integrative Neuroscience, M.Sc.
Philosophy of Neuroscience, B.A.

**Comment by qgeissmann** [comment]
This mostly happens when status (column 4) is not `1` (e.g. `51` or `54`). Therefore, I am simply going to exclude data when status is **not** `1`.
