### ISSUE TITLE
Dead animals

### ISSUE THREAD

**Issue by estebanbeck** [gilestrolab/rethomics#23]
We need to implement a filter to remove, after Sleep analysis, the dead animals.

**Comment by qgeissmann** [comment]
agreed. I will be working on that.

**Comment by estebanbeck** [comment]
I have tried, but I have failed!! Before implement it let me show you what I have done!

**Comment by qgeissmann** [comment]
From the documentation (see `?curateDeadAnimals`):

```R
data(dam_data)
# we add a `moving` column to the data
dt <- dam_data[,
           sleepDAMAnnotation(.SD),
           by=key(dam_data)]
# let us have a look at the pattern of movement.
# Some animals (e.g. 06, 21, 24) died early.
overviewPlot(moving,dt,normalise_var_per_id = FALSE)
```
![before](https://cloud.githubusercontent.com/assets/1399684/9335669/3dc8ce04-45cd-11e5-81da-f2b4cb939666.png)

**Then this is how we curate the data**

```R
dt_curated <- dt[,curateDeadAnimals(.SD,hours(15)),by=key(dt)]
# Note that some data has been removed.
# Also, no data was there for region_id == 06, therefore, it is removed altogether
overviewPlot(moving, dt_curated, normalise_var_per_id = FALSE)
```
![after](https://cloud.githubusercontent.com/assets/1399684/9335672/4197c35a-45cd-11e5-857c-78cc4637aa29.png)

**Comment by estebanbeck** [comment]
Good! Now the only thing is to decide what to do with the dead animals, should we consider them in the analysis? Or because they died during the exp we should removed completely? 
We can do this using the lifespam tool, then make a map, and remove the animales that don't have a maximum lifespam.
