### ISSUE TITLE
fetchDAMData fails

### ISSUE THREAD

**Issue by zoranne** [gilestrolab/rethomics#25]
fetchDAMData cannot read query, although query is correct, including column names when doing print(query).

Error message:

'Error in setnames(files_info, c("yyyy", "mm", "mmdd", "file")) : 
x has no column names'

**Comment by zoranne** [comment]
using "read.csv" instead of "fread" does not fix the issue

**Comment by qgeissmann** [comment]
could you enclose your query please?

**Comment by zoranne** [comment]
github only lets me attach pictures, no csv, weird. here we go.

On 31 August 2015 at 14:16, Quentin Geissmann <notifications@github.com>
wrote:

> could you enclose your query please?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gilestrolab/rethomics/issues/25#issuecomment-136368294>
> .
>



-- 
___________________________________
PhD Life Sciences Candidate
Graduate School
Life Sciences Department
South Kensington Campus
Imperial College London
___________________________________
Integrative Neuroscience, M.Sc.
Philosophy of Neuroscience, B.A.

**Comment by qgeissmann** [comment]
NP, Can you paste your `R` code pls?

**Comment by zoranne** [comment]
'library(rethomics)
DAILY_DATA_DIR <- "/C:/Users/anne/Documents/PhDProject+Misc/dam_daily"
QUERY_PATH <- "C:/Users/anne/Google Drive/PhDProjects/Scripts/rethomics/Queries/DAMquery-dummy.csv"

query <- fread(QUERY_PATH, sep=",")
query
dt <- fetchDAMData(DAILY_DATA_DIR,query,reference_hour = 9,tz = "BST", FUN=sleepAnnotation)'

and a direct query such as the one below throws the same error message

'query <- data.table(date="2015-06-18",
                     machine_name=c("GGSM-004","GGSM-006"),
                     genotype=c("102914/PDF","41787/PDF"))
query'

**Comment by qgeissmann** [comment]
you mean the first one works, but not the second?

**Comment by zoranne** [comment]
neither of them works, both give the same error message

**Comment by qgeissmann** [comment]
1. Can you list exactly what is in your `DAILY_DATA_DIR` (`dam_daily`).
2. I would **strongly suggest** (unless you have a good reason) to use `sleepDAMAnnotation`, not `sleepAnnotation`; the latter infers sleep from video data.

**Comment by zoranne** [comment]
1. dam_daily contains a copy of the dam_daily on the server (years 2013-2015 until 28/08/2015)
2. yes, sure

**Comment by qgeissmann** [comment]
1. do you actually have `dam_daily/2015/...` or `dam_daily/damDaily/2015/...`

**Comment by zoranne** [comment]
1. dam_daily/2013 etc

**Comment by qgeissmann** [comment]
Weird, I cannot reproduce that on my computer. You have checked that the files are actually there?
It seems that it fails to list available files somehow.

**Comment by qgeissmann** [comment]
Can you run this:

```R
fs <- list.files( DAILY_DATA_DIR,pattern="M...*\\.txt",recursive = T)
print(fs) 
##HERE, YOU SHOULD HAVE A LONG LIST OF FILES

fields <- strsplit(fs,"/")
valid_files <- sapply(fields,length) == 4

fs <- fs[valid_files]
print(fs)
## THIS IS A FILTERED LIST KEEPING ONLY VALID FILES
```

**Comment by zoranne** [comment]
yes, it throws: character(0).
the files are present in dam_daily, though.

i'm trying to run this on Windows, maybe that's a problem?

**Comment by ggilestro** [comment]
replace all the \ with \\

--
Giorgio F. Gilestro
http://gilest.ro

**Comment by qgeissmann** [comment]
the first one is `character(0)`? can you **remove the +** from the directory name? Or copy /move files to another dir?

@ggilestro R uses double `\` to escape `.` in regex (http://stackoverflow.com/questions/18523880/replace-two-dots-in-a-string-with-gsub)

**Comment by zoranne** [comment]
// vs / doesn't help

**Comment by qgeissmann** [comment]
@zoranne 
can you replace:

`DAILY_DATA_DIR <- "/C:/Users/anne/Documents/PhDProject+Misc/dam_daily"`

with 
DAILY_DATA_DIR <- "C:/Users/anne/Documents/PhDProject+Misc/dam_daily"

**no first slash**

**Comment by zoranne** [comment]
don't believe it. thanks quentin.

**Comment by zoranne** [comment]
yes, man kann gar nicht so dumm denken, wie man kann :p
