### ISSUE TITLE
Rethomics should include activity/inactivity peak analysis

### ISSUE THREAD

**Issue by zoranne** [gilestrolab/rethomics#27]
Rethomics should include a function to return the presence and timing of activity/inactivity peaks.
To find activity peaks, could use the diff function. How to tie that to the dt keys etc. though? 
Or would it make more sense to go mathematically a bit more fancy and calculate local maxima and minima?

findpeaks <- function (x, thresh = 0) 
{
  pks <- which(diff(sign(diff(x, na.pad = FALSE)), na.pad = FALSE) < 0) + 2
  if (!missing(thresh)) {
    pks[x[pks - 1] - x[pks] > thresh]
  }
  else pks
}

**Comment by zoranne** [comment]
Solution as per Quentin

findPeaks <- function(data, k=61,minpeak=.5){
  dt <- copy(data)
  
  if(nrow(data) < 2*k){
    warning("Skipping one data table...")
    return(NULL)
  }
  kernel <- rep(1/k, k)
  dt[,smooth_activity := filter(activity,kernel)]
  dt <- na.omit(dt)
  x <- dt[,t]
  y <- dt[, smooth_activity]
  peaks <- peakwindow(x, y, minpeak=minpeak)
  if(nrow(peaks$peaks) == 0){
    warning("No peaks found")
    return(NULL)
  }
  out <- as.data.table(peaks$peaks)
  return(out)
}

out <- small_dt[,
                findPeaks(.SD),
                by=key(small_dt)]

out[,t_h := x/hours(24)]
out_morning <- out[t_h>2 & t_h <2.125]
out_morning[,
            .N,
            by=key(out)]

**Comment by qgeissmann** [comment]
This is not planned to be in the package itself, but we could include it in the tutorials.
closing
