### ISSUE TITLE
loadEthoscopeData should print a message when cache_files=T

### ISSUE THREAD

**Issue by nazabic** [gilestrolab/rethomics#34]
When cache_files = T the user waits a lot while the files are copied, it would be nice to have a message like...'Copying files...' and then 'Loading ROI etc.'

**Comment by qgeissmann** [comment]
Sure, we can do that, good idea.
Also, we need to compute a checksum of local and remote files. As it will not reload files that are different (e.g. updated upstream) but have the same name.

**Comment by qgeissmann** [comment]
We do not cache files this way anymore. see #44
