### ISSUE TITLE
Ethoscope front page

### ISSUE THREAD

**Issue by estebanbeck** [gilestrolab/rethomics#35]
Maybe it would be a good idea to have a comment field when starting an ethoscope, and the first 10 letter or so, could be another column in the front page. For instant to add the name of the person using a certain device. Also be able to sort the front page by the different columns would be nice.

**Comment by qgeissmann** [comment]
Yo, I am moving this on the ethoscope repo.

**Comment by qgeissmann** [comment]
in fact it is a duplicate of https://github.com/gilestrolab/ethoscope/issues/25
