### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by estebanbeck** [gilestrolab/rethomics#38]
Hi! the documentation, tutorial and readme are not there anymore.

**Comment by qgeissmann** [comment]
This will be solved by a website coupled with travis jobs to generate tutorials and doc. WIP

**Comment by qgeissmann** [comment]
the doc and tutorial should now be centralised at http://gilestrolab.github.io/rethomics/. They are rebuilt for every commit in master, and also once a week (all by travis-ci).
