### ISSUE TITLE
Error with DAM data

### ISSUE THREAD

**Issue by florenciafernandez** [gilestrolab/rethomics#39]
Hi! I'm Florencia, from Argentina, and I'm writing here because I've been having some issues analyzing my data with rethomics. I collect my data from Trikinetics monitors and when I try to run this command `dt <- loadDailyDAM2Data(DAILY_DATA_DIR, query,reference_hour = 09.0, FUN=sleepDAMAnnotation)`, I keep getting the following error:

```
Error in FUN(X[[i]], ...) : 
  There is apparently no data in this range of dates
```

Do you have any idea of what could be happening here? I also tested the script with some old data that I have and it worked perfectly (please bear in mind that I'm not an expert coder)

**Comment by qgeissmann** [comment]
hey there,
Looks like an issue with your query.
Specifically, one of the date range does not seem to contain any data (I would double check the dates).
Any chance you can attach your query (drag & drop the file in a message)?
what you can do to help debugging, is to make the query simpler.
for instance, you can test the first two rows:

```
dt <- loadDailyDAM2Data(DAILY_DATA_DIR, query[1:2] ,reference_hour = 09.0, FUN=sleepDAMAnnotation
```
then the first three with `query[1:3]` and so on until it fails. this way, you can know speciffically which row in the query is giving an error. 
good luck!

**Comment by qgeissmann** [comment]
Any progress on that?

**Comment by florenciafernandez** [comment]
I'm sorry that I didn't reply before, I've been trying a lot of different
things and it still doesn't work. My guess is that there might be something
wrong with the data itself, maybe in the acquisition process something
happened and there is information missing in the .txt file (mainly because
the script works with some old data that I tried). I'm going to run the
experiment again soon and if I have trouble again, I'll send you another
message.
I have another question for you: As I have only two Trikinetics monitors
and I need to run an experiment with three different experimental groups, I
need to use the same monitor for two groups. Is there a way to modify the
script in order to analyze a certain group of channels in a monitor?

Thanks a lot!
F.


2016-01-18 15:24 GMT-03:00 Quentin Geissmann <notifications@github.com>:

> Any progress on that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gilestrolab/rethomics/issues/39#issuecomment-172612470>
> .
>



-- 
F.

**Comment by estebanbeck** [comment]
Hi Flor!

If you have more than one genotype per monitor you need to add a column in the query (region_id), the  accepted values are 1, 2, 3, etc. If you add this column then you need to include all the channels you want to analyse for each monitor, each one as an independent raw.

So, you will have something like (check that this is an example for our monitors -ethoscopes-, not for the DAMs, but still you get the idea!):

date	machine_name	region_id	genotype	SD	treatment
2015-12-03	ETHOSCOPE_001	1	1-W1118	T	1-w1118-SD
2015-12-03	ETHOSCOPE_001	2	1-W1118	T	1-w1118-SD
2015-12-03	ETHOSCOPE_001	3	1-W1118	T	1-w1118-SD
2015-12-03	ETHOSCOPE_001	4	1-W1118	T	1-w1118-SD
2015-12-03	ETHOSCOPE_001	5	1-W1118	T	1-w1118-SD
2015-12-03	ETHOSCOPE_001	6	1-W1118	T	1-w1118-SD
2015-12-03	ETHOSCOPE_001	7	1-W1118	T	1-w1118-SD
2015-12-03	ETHOSCOPE_001	8	1-W1118	T	1-w1118-SD
2015-12-03	ETHOSCOPE_001	9	1-W1118	T	1-w1118-SD
2015-12-03	ETHOSCOPE_001	10	1-W1118	T	1-w1118-SD
2015-12-03	ETHOSCOPE_001	11	1-W1118	T	1-w1118-SD
2015-12-03	ETHOSCOPE_001	12	1-W1118	T	1-w1118-SD
2015-12-03	ETHOSCOPE_001	13	2-CNMa01	T	2-CNMa01-SD
2015-12-03	ETHOSCOPE_001	14	2-CNMa01	T	2-CNMa01-SD
2015-12-03	ETHOSCOPE_001	15	2-CNMa01	T	2-CNMa01-SD

cheers!

**Comment by qgeissmann** [comment]
I have just tried simply loading the file:

```R
rethomics:::loadSingleDAM2File("0414M001.txt")
```

This works fine for me. can you tell me if this works for you too?

**Comment by florenciafernandez** [comment]
Still not working :(
I couldn't upload the .zip folder with my DAMfolder data directly here, so I hosted it the following link:
http://www.filedropper.com/2015

I'm also copying here the script that I'm using until the line where it gets stucked:

rm(list = ls(all = TRUE))
.libPaths("C:/Program Files/R/R-3.2.0/library")
library(rethomics)
DAILY_DATA_DIR <- "C:/Users/Nara/Documents/Florencia Fernández/Experimentos/Comportamiento/Input PySolo/DAMfolder"
query = data.table(start_date="yyyy-mm-dd", stop_date = "yyyy-mm-dd",                 
                              machine_id=c("M001","M002"), 
                              treatment=c("control","experimento"))
print(query)
dt <- loadDailyDAM2Data(DAILY_DATA_DIR, query,reference_hour = 09.0, FUN=sleepDAMAnnotation)

**Comment by qgeissmann** [comment]
@florenciafernandez 
Is that your actual code?
Your query cannot work:

```R
query = data.table(start_date="yyyy-mm-dd", stop_date = "yyyy-mm-dd",
    machine_id=c("M001","M002"),
    treatment=c("control","experimento"))
```
You have to actually provide a start date and stop date, as number.
Please, can you send us an example of failure with an actual query?

It works for me if I make a query such as:

```R
query = data.table(start_date="2015-04-14", stop_date = "2015-12-15",
	machine_id=c("M001","M002"),
	treatment=c("control","experimento"))
```

**Comment by florenciafernandez** [comment]
Oh, this is a little embarrassing for me! I just, by mistake, sent you the
structure of the query that I use, but I actually use a start date and stop
date, as number. I just wrote it that way so I can easily change it
depending on the experiment date.
The exact same query that you sent me doesn´t work in my computer, as a
matter of fact. Neither if I just use 2015-04-14 as start and stop date.
Actually, the only files that I could make work are the ones from May.

> rm(list = ls(all = TRUE))
> .libPaths("C:/Program Files/R/R-3.2.0/library")
> library(rethomics)
> DAILY_DATA_DIR <- "C:/Users/Nara/Documents/Florencia
Fernández/Experimentos/Comportamiento/Input PySolo/DAMfolder"
> query = data.table(start_date="2015-04-14", stop_date = "2015-12-15",

+                    machine_id=c("M001","M002"),
+                    treatment=c("control","experimento"))
> print(query)
   start_date  stop_date machine_id   treatment
1: 2015-04-14 2015-12-15       M001     control
2: 2015-04-14 2015-12-15       M002 experimento
> dt <- loadDailyDAM2Data(DAILY_DATA_DIR, query,reference_hour = 09.0,
FUN=sleepDAMAnnotation)
[1] "Reading C:/Users/Nara/Documents/Florencia
Fernández/Experimentos/Comportamiento/Input
PySolo/DAMfolder/2015/04/0414/0414M001.txt."
Error in FUN(X[[i]], ...) :
  There is apparently no data in this range of dates
In addition: Warning messages:
1: In strptime(datetime, "%d %b %y %H:%M:%S", tz = tz) :
  unknown timezone 'BST'
2: In as.POSIXct.POSIXlt(strptime(datetime, "%d %b %y %H:%M:%S", tz = tz)) :
  unknown timezone 'BST'
3: In min(valid_dt[, idx]) :
  no non-missing arguments to min; returning Inf
4: In max(valid_dt[, idx]) :
  no non-missing arguments to max; returning -Inf

2016-01-26 17:55 GMT+00:00 Quentin Geissmann <notifications@github.com>:

> @florenciafernandez <https://github.com/florenciafernandez>
> Is that your actual code?
> Your query cannot work:
>
> query = data.table(start_date="yyyy-mm-dd", stop_date = "yyyy-mm-dd",
>     machine_id=c("M001","M002"),
>     treatment=c("control","experimento"))
>
> You have to actually provide a start date and stop date, as number.
> Please, can you send us an example of failure with an actual query?
>
> It works for me if I make a query such as:
>
> query = data.table(start_date="2015-04-14", stop_date = "2015-12-15",
>     machine_id=c("M001","M002"),
>     treatment=c("control","experimento"))
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gilestrolab/rethomics/issues/39#issuecomment-175142804>
> .
>



-- 
F.

**Comment by qgeissmann** [comment]
Can you try that on the latest version of rethomics (reinstall the package) :),
