### ISSUE TITLE
Plots should be able to show different backgrounds according to time

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/rethomics#50]
This would allow to have show LD phases in the graphs

**Comment by qgeissmann** [comment]
This is now possible with `makeLDAnnotation`.

For instance:
```R
data(sleep_sexual_dimorphism)
my_data <- sleep_sexual_dimorphism

p <- overviewPlot(asleep,my_data,condition=sex)
p <- makeLDAnnotation(p, days)
print(p)

p <- ethogramPlot(asleep,my_data,condition=sex,error_bar="sem")
p <- makeLDAnnotation(p, days)
print(p)
```

![annot_overviewplot](https://cloud.githubusercontent.com/assets/1399684/13047346/43dff67c-d3d6-11e5-8bfd-0a11d5126d74.png)

![annot_ethogramplot](https://cloud.githubusercontent.com/assets/1399684/13047345/43deaa10-d3d6-11e5-991b-b62edb880db2.png)

need to work a bit on the `offset` argument and aesthetics, but of for now;)

**Comment by ggilestro** [comment]
Can we optionally use the sensor data from the smart incubators for this?
It would be nice to integrate real temp, humidity and light into the data.

--
Giorgio F. Gilestro
http://gilest.ro

**Comment by qgeissmann** [comment]
In principle, it is possible. 

It requires a bit of work from the user at this stage as one needs to map incubators to device (the device does not know which incubator it is in).

Also, these plots average several animals from multiple dates/incubators, so we need to keep in mind that we not guaranteed to have equal values for light/humidity/temp over replicates...

One thing you (users) can start doing is add an `incubator` variable in the queries for future mapping.
This way, sensor data can be treated as individual variable (just like x position, you would have temperature).
