### ISSUE TITLE
Sample Data Tutorial link broken

### ISSUE THREAD

**Issue by nli8888** [gilestrolab/rethomics#63]
The link for data (where it says "You can find it here") in the Sample Data tutorial page (http://gilestrolab.github.io/rethomics/tutorial/sample_data.html) is broken.

**Comment by qgeissmann** [comment]
the new link upstream is https://imperialcollegelondon.box.com/v/rethomics-tutorial-data. Still need to rebuild tutorial through travis... (see #64)

**Comment by qgeissmann** [comment]
tutorial data now lives in a [versioned DOI](https://zenodo.org/record/826874) on zenodo
