### ISSUE TITLE
curate dead animals

### ISSUE THREAD

**Issue by estebanbeck** [gilestrolab/rethomics#77]
I tried to run: 
dt <- dt[,curateDeadAnimals(.SD, max_immobile_live=hours(4)), by=id]

and I got:

 Show Traceback
 
 Rerun with Debug
 Error in data.table(delta_t = sdt[, delta_t], bout_id = inverse.rle(r),  : 
  could not find function "data.table" 

The funny thing is that I have been using this function 3 days ago with no problem...

**Comment by pepelisu** [comment]
Have you check that data.table is marked in the Packages panel of Rstudio? Seems that the package can not be found:
`could not find function "data.table"`

**Comment by estebanbeck** [comment]
Ok, it worked! But any idea why it would not automatically load?

**Comment by qgeissmann** [comment]
Still need to implement it in the new framework: https://github.com/rethomics/sleepr/issues/2
